### ISSUE TITLE
test: randomly failed on GitHub Actions: Windows ( tempdir not removed )

### ISSUE THREAD

**Issue by fbucek** [fbucek/nafta#9]
Randomly failing on GitHub Actions Windows Server build - not removing removing `test.db` from temporary folder

**Not possible to verify bug on local installation of Windows 10**

``` 
thread 'sqlite::tests::test_lifecycle' panicked at 'assertion failed: !dirpath.exists()', src\sqlite.rs:96:9
```

Sometimes it panicked on `doc` tests

```
stderr:
thread 'main' panicked at 'assertion failed: !path.exists()', src\lib.rs:15:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

test src\lib.rs -  (line 7) ... FAILED

failures:

failures:
    src\lib.rs -  (line 7)
```

**Comment by fbucek** [comment]
Problem not solved.
On Windows machine not problem. Runned multiple times no problems at all.
But GitHub Actions is problem. No clue why.
